apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers
  labels:
    app: customers
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      #imagePullSecrets:
      #- name: all-icr-io
      restartPolicy: Always
      containers:
      - name: customers
        image: cluster-registry:32000/customers:latest
        #image: nyu-project
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          - name: RETRY_COUNT
            value: "10"
          - name: DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: postgres-creds
                key: database_uri
          #- name: PORT
          #  value: "8080"
          #- name: FLASK_APP
          #  value: wsgi:app
          #- name: FLASK_DEBUG
          #  value: "True"
          #- name: GUNICORN_BIND
          #  value: "0.0.0.0:8080"
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 30
          httpGet:
            path: /health
            port: 8080
        resources:
          limits:
            cpu: "0.50"
            memory: "128Mi"
          requests:
            cpu: "0.25"
            memory: "64Mi"
